### ISSUE TITLE
Add transaction feature to rollback operations on exception

### ISSUE THREAD

**Issue by Doraku** [Doraku/DefaultUnDo#1]
some kind of
```csharp
IUnDoManager manager;

using (IUnDoTransaction transaction = manager.BeginTransaction())
{
    ...
    ...

    // else everything recorded is undone and it is not integrated on the operations history
    transaction.Commit();
}
```

**Comment by earloc** [comment]
Maybe this could also come Handy when used via ambient transactions / [TransactionScipes](https://docs.microsoft.com/en-us/dotnet/framework/data/transactions/implementing-an-implicit-transaction-using-transaction-scope#:~:text=%20A%20TransactionScope%20object%20has%20three%20options%3A%20,no%20ambient%20transaction%20as%20a%20result.%20More%20) , like ADO.NET is aware of:

**Comment by Doraku** [comment]
Yep that's something I had in mind too, definitely going to look into TransactionScope.

**Comment by Doraku** [comment]
After finally giving some thinking to this, using `TransactionScope` seems ill fitted:
- only available from netstandard2.0
- it makes sense to handle every changes made within a transaction as a single group so it seems redondant with the existing `BeginGroup` feature
- no overload of `TransactionScope` to hijack to provide a description for `IUnDo` instances

As such I am leaning to directly re purpose `BeginGroup` as a transaction declaration, forcing user to commit the group/transaction before the dispose for it to not be automatically rolled-back.
